import unittest

from sglang.test.ascend.test_ascend_utils import GTE_QWEN2_1_5B_INSTRUCT_WEIGHTS_PATH
from sglang.test.ascend.test_embedding_base import BaseEmbeddingTest
from sglang.test.ci.ci_register import register_npu_ci
from sglang.test.test_utils import CustomTestCase

register_npu_ci(
    est_time=400,
    suite="full-1-npu-a3",
    nightly=True,
)


class TestGteQwen2(BaseEmbeddingTest, CustomTestCase):
    """Testcase: This test case verifies that the embeddings generated by the iic/gte_Qwen2-1.5B-instruct model in the
    SGLang framework closely match those from the Hugging Face implementation with a tolerance of 1e-5.

    [Test Category] Model
    [Test Target] iic/gte_Qwen2-1.5B-instruct
    """

    MODELS = [
        (GTE_QWEN2_1_5B_INSTRUCT_WEIGHTS_PATH, 1, 1e-5),
    ]


if __name__ == "__main__":
    unittest.main()
