import unittest

from sglang.test.ascend.test_ascend_utils import CLIP_VIT_LARGE_PATCH14_336_WEIGHTS_PATH
from sglang.test.ascend.test_embedding_base import BaseEmbeddingTest
from sglang.test.ci.ci_register import register_npu_ci
from sglang.test.test_utils import CustomTestCase

register_npu_ci(
    est_time=400,
    suite="full-1-npu-a3",
    nightly=True,
)


class TestClipVitLargePatch14(BaseEmbeddingTest, CustomTestCase):
    """Testcase: This test case verifies that the embeddings generated by the AI-ModelScope/clip-vit-large-patch14-336
    model in the SGLang framework closely match those from the Hugging Face implementation with a tolerance of 0.22.

    [Test Category] Model
    [Test Target] AI-ModelScope/clip-vit-large-patch14-336
    """

    MODELS = [(CLIP_VIT_LARGE_PATCH14_336_WEIGHTS_PATH, 1, 0.3)]
    DEFAULT_MAX_LENGTH = 76


if __name__ == "__main__":
    unittest.main()
