import unittest

from sglang.test.ascend.test_ascend_utils import QWEN3_EMBEDDING_8B_WEIGHTS_PATH
from sglang.test.ascend.test_embedding_base import BaseEmbeddingTest
from sglang.test.ci.ci_register import register_npu_ci
from sglang.test.test_utils import CustomTestCase

register_npu_ci(
    est_time=400,
    suite="full-1-npu-a3",
    nightly=True,
)


class TestQwen3Embedding8B(BaseEmbeddingTest, CustomTestCase):
    """Testcase: This test case verifies that the embeddings generated by the Qwen/Qwen3-Embedding-8B model in the
    SGLang framework closely match those from the Hugging Face implementation with a tolerance of 1e-5.

    [Test Category] Model
    [Test Target] Qwen/Qwen3-Embedding-8B
    """

    MODELS = [
        (QWEN3_EMBEDDING_8B_WEIGHTS_PATH, 1, 1e-5),
    ]


if __name__ == "__main__":
    unittest.main()
